# Use root/example as user/password credentials
version: '3.1'

services:
  techexamples-mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: techpw
  techexamples-redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
  techexamples-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node